# Nombre de la app
spring.application.name=challenge

# Tiempo de cache en minutos
cache.percentage.ttl=30

# Conexion a la base de datos usando variables de entorno:
# Usa SPRING_DATASOURCE_HOST, que en Docker se establecera a "db"
spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/${POSTGRES_DB:challengeDB}

# Credenciales, con valores por defecto
spring.datasource.username=${POSTGRES_USER:challengeuser}
spring.datasource.password=${POSTGRES_PASSWORD:challengepass}

# Configuracion de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuracion de Logs
logging.level.org.springframework=INFO
logging.level.com.api.challenge=DEBUG
